# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pharmacogenetics Analysis Pipeline
email: graeme.ford@tuks.co.za
description: >- # this means to ignore newlines until "domain:"
  A computational pipeline to analyse variant-call data.
domain: "tuks-icmm.github.io"
baseurl: "/Pharmacogenetic-Analysis-Pipeline" # the subpath of your site, e.g. /blog
url: "https://tuks-icmm.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: G-Kodes

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.3.0"

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap

color_scheme: "dark"

aux_links:
  "GitHub":
    - "https://github.com/Tuks-ICMM/Pharmacogenetic-Analysis-Pipeline"
  "ICMM":
    - "https://www.up.ac.za/institute-for-cellular-and-molecular-medicine"
aux_links_new_tab: true

excerpt_separator: "<!--end sample-->"

ga_tracking: G-5BE9TP7NV4
ga_tracking_anonymize_ip: true

callouts:
  warning:
    title: Warning
    color: red
  normal:
    title: Note
    color: purple
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
