name: Snakemake Integrity Test
on:
  pull_request:
    branches: 
      - "main"

jobs:
  Test-Snakemake:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.19.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--lint'
      - name: Testing
        uses: snakemake/snakemake-github-action@v1.19.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
          stagein: '' # additional preliminary commands to run (can be multiline)
