name: Snakemake Unit Tests
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: "pip install -r requirements.txt"
      - name: Dry Run
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: "."
          snakefile: "workflow/Snakefile"
          args: "--dry-run"

      # Deactivated testing in light of https://github.com/snakemake/snakemake-github-action/issues/18
      # - name: Testing
      #   uses: snakemake/snakemake-github-action@v1.23.0
      #   with:
      #     directory: ".test"
      #     snakefile: "workflow/Snakefile"
      #     args: "--cores 1 --use-conda --conda-cleanup-pkgs cache"
      #     stagein: "" # additional preliminary commands to run (can be multiline)
