name: Snakemake Unit Tests
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: ".test"
          snakefile: "workflow/Snakefile"
          args: "--lint"

      - name: Testing
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: ".test"
          snakefile: "workflow/Snakefile"
          args: "--cores 1 --use-conda --conda-cleanup-pkgs cache"
          stagein: "" # additional preliminary commands to run (can be multiline)
